name: algodart
description: A simple command-line application.
version: 1.0.0
homepage: http://www.mehmetesen.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main
